### ISSUE TITLE
Backend master issue

### ISSUE THREAD

**Issue by MichaelPesce** [CATALOG-Historic-Records/orphaned-wells-ui-server#3]
- [x] Set up backend server with fastapi and uvicorn
   - #1 
- [x] Set up mongodb connection to store user, project, and record data
   - #2 
- [x] Add functionality to process image using document ai processor
   - #2 
- [x] Add functionality to store parsed image data in mongodb collection
   - #2 
- [x] Add functionality to store uploaded documents in google cloud storage
   - #2 
- [x] Create API for downloading records from DB in csv format
- [ ] Set up pytest for testing python code
- [x] Create APIs for:
   - [x] updating projects
   - [x] updating records
      - #4 
   - [x] deleting projects
      - #4 
   - [x] deleting records
      - #4 
- [x] Set up google cloud engine VM to host backend 
- [x] Add login/authentication
   - #5 
- [x] Incorporate trained processor(s)
